INSERT INTO clientes (nombre, apellido, email, fecha) VALUES('Carlos','Mendoza','cmendoza@gmail.com','2023-8-25');
INSERT INTO clientes (nombre, apellido, email, fecha) VALUES('Jazmin','Diaz','jaz@gmail.com','2023-8-25');
INSERT INTO clientes (nombre, apellido, email, fecha) VALUES('Jessy', 'Rangel', 'jessy@gmail.com', '2023-8-25');
INSERT INTO clientes (nombre, apellido, email, fecha) VALUES('Adriana', 'Ruiz', 'Ruiz@gmail.com', '2023-8-25');
INSERT INTO clientes (nombre, apellido, email, fecha) VALUES('Daniela', 'Perez', 'dani@gmail.com', '2023-8-25');
INSERT INTO clientes (nombre, apellido, email, fecha) VALUES('Juan', 'Mendez', 'Juan@gmail.com', '2023-8-25');
INSERT INTO clientes (nombre, apellido, email, fecha) VALUES('Alicia', 'Hernandez', 'ali@gmail.com', '2023-8-25');
INSERT INTO clientes (nombre, apellido, email, fecha) VALUES('Thalia', 'Herrera', 'Thaliz@gmail.com', '2023-8-25');
INSERT INTO clientes (nombre, apellido, email, fecha) VALUES('Mitzi', 'Lopez', 'mit@gmail.com', '2023-8-25');
INSERT INTO clientes (nombre, apellido, email, fecha) VALUES('Monserrath', 'Trujillo', 'monse@gmail.com', '2023-8-25');
